<?php

/**
 * @file
 * Contains di_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function di_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the di_paragraphs module.
    case 'help.page.di_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paragraphs and shared fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function di_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],
    // 'field__paragraph__field_media__media' => [
    //   'base hook' => 'paragraph',
    // ],
    'paragraph__grid_column' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__grid_row' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__heading' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__media' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__section' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__text' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__view' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__section().
 * Prepares variables for paragraph--section.html.twig.
 */
function di_paragraphs_preprocess_paragraph__section(&$variables) {
  $p = $variables['paragraph'];

  // Setup palette color class name variable.
  $palette = $p->field_section_palette_list->getValue();
  $palettename = !empty($palette[0]['value']) ? $palette[0]['value'] : 'none';
  $variables['palette'] = 'bg-' . $palettename;

  // Setup width variable for template
  if(!$p->field_section_width->isEmpty()){
    switch ($p->field_section_width->get(0)->value) {
      case "1":
        $width = "section-content-width";
        break;
      case "2":
        $width = "section-full-width";
        break;
    }
    $variables['width'] = $width;
  }
}
